# noinspection SqlNoDataSourceInspectionForFile
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin', 'admin@admin.com', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'enabled@user.com', 1, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (3, 'disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'disabled@user.com', 0, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (3, 1);

INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (0,'costtype.none',0,0,0,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (1,'costtype.income.current.account',1,1,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (2,'costtype.expense.current.account',0,1,1,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (3,'costtype.expense.current.account.erroneous',0,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (4,'costtype.deposit',1,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (5,'costtype.withdrawal',0,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (6,'costtype.expense.other.account.ignore',0,0,0,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (7,'costtype.expense.other.account.erroneous',0,1,0,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (8,'costtype.expense.travel.other.account.erroneous',0,1,0,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (9,'costtype.expense.travel',0,1,1,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (10,'costtype.saving.in',0,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (11,'costtype.creditcard.partial.payment',0,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (12,'costtype.vat.return',0,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (13,'costtype.business.food',0,0,1,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (14,'costtype.business.car',0,1,1,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (15,'costtype.saving.out',1,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (16,'costtype.investment.depreciate',0,1,1,0,1);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (17,'costtype.private.in',0,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (18,'costtype.private.out',1,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (19,'costtype.business.car.other.account',0,1,0,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (20,'costtype.business.food.other.account',0,0,0,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (21,'costtype.business.travel.credit.card',0,1,0,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (22,'costtype.business.literature.credit.card.no.vat',0,0,0,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (23,'costtype.business.car.depreciation',0,0,0,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (24,'costtype.business.car.fiscal.income',0,0,0,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (25,'costtype.depreciation',0,0,0,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (26,'costtype.investment.depreciate.other.account',0,1,0,0,1);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (27,'costtype.advertorial',0,1,1,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (28,'costtype.advertorial.no.vat',0,0,1,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (29,'costtype.income.tax',0,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (30,'costtype.income.tax.return',1,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (31,'costtype.road.tax',0,0,1,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (32,'costtype.expense.creditcard',0,1,0,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (33,'costtype.interest',1,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (34,'costtype.vat.return.incoming.other.account',1,0,0,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (35,'costtype.vat.correction.depreciation',0,0,0,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (36,'costtype.vat.correction.private',0,1,0,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (38,'costtype.invoice.paid',1,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (39,'costtype.invoice.sent',0,1,0,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (40,'costtype.repurchase',0,1,1,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (41,'costtype.office',0,1,1,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (42,'costtype.office.interest',0,0,1,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (43,'costtype.office.depreciation',0,0,0,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (44,'costtype.office.other.account',0,0,0,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (45,'costtype.office.discount',1,1,1,1,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (46,'costtype.income.current.account.ignore',1,0,1,0,0);
INSERT INTO KOSTENSOORT (ID, OMSCHRIJVING, BIJSCHRIJVING, BTW_VERREKENBAAR, BALANS_MEETELLEN, AFTREKBAAR, INVESTERING) VALUES (47,'costtype.expense.eu',0,1,1,1,0);












